#!/bin/bash
cd ../dependencies/glslang

mkdir build

cd build

cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
ninja

cd ..

mkdir build_debug

cd build_debug

cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
ninja
