#!/bin/bash

cd ..

cp dependencies/lua/libluajit.so app/libluajit-5.1.so.2

cp ../Intrinsic_Dependencies/dependencies/physx3.4/lib/libPx*PROFILE_x64.so app/.
cp ../Intrinsic_Dependencies/dependencies/physx3.4/lib/libPhysX3*PROFILE_x64.so app/.

cd scripts_linux
