FIND_PATH(BUGSPLAT_INCLUDE_DIR bugsplat.h
  PATH_SUFFIXES include
  PATHS
  ${CMAKE_SOURCE_DIR}/dependencies/bugsplat
)

FIND_LIBRARY(BUGSPLAT_LIBRARY
  NAMES BugSplat64
  PATH_SUFFIXES lib
  PATHS
  ${CMAKE_SOURCE_DIR}/dependencies/bugsplat
)

SET(BUGSPLAT_LIBRARIES
	debug ${BUGSPLAT_LIBRARY}
	optimized ${BUGSPLAT_LIBRARY}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BUGSPLAT  DEFAULT_MSG  BUGSPLAT_INCLUDE_DIR BUGSPLAT_LIBRARY)

MARK_AS_ADVANCED(BUGSPLAT_INCLUDE_DIR BUGSPLAT_LIBRARY)
